name: engens-conda-env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.01.10=h06a4308_0
  - libedit=3.1.20221030=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=21.2.2=py36h06a4308_0
  - python=3.6.7=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=58.0.4=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - mdtraj
  - msmtools
  - pyemma
  - dm-tree
  - git
  - pip:
      - absl-py==0.15.0
      - alembic==1.7.5
      - anyio==3.3.4
      - argon2-cffi==21.1.0
      - astunparse==1.6.3
      - async-generator==1.10
      - attrs==21.2.0
      - babel==2.9.1
      - backcall==0.2.0
      - bhmm==0.6.3
      - biopython==1.79
      - bleach==4.1.0
      - cached-property==1.5.2
      - cachetools==4.2.4
      - certifi==2021.10.8
      - certipy==0.1.3
      - cffi==1.15.0
      - charset-normalizer==2.0.7
      - clang==5.0
      - cloudpickle==2.2.1
      - contextvars==2.4
      - cryptography==35.0.0
      - cycler==0.11.0
      - dataclasses==0.8
      - decorator==5.1.0
      - defusedxml==0.7.1
      - dill==0.3.4
      - entrypoints==0.3
      - flatbuffers==1.12
      - gast==0.4.0
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==1.1.2
      - grpcio==1.48.2
      - h5py==3.1.0
      - humanfriendly==10.0
      - idna==3.3
      - immutables==0.16
      - importlib-metadata==4.8.2
      - importlib-resources==5.4.0
      - ipykernel==5.5.6
      - ipython==7.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==7.6.5
      - jedi==0.18.0
      - jinja2==3.0.3
      - joblib==1.1.0
      - json5==0.9.6
      - jsonschema==3.2.0
      - jupyter-client==7.0.6
      - jupyter-core==4.9.1
      - jupyter-server==1.11.2
      - jupyter-telemetry==0.1.0
      - jupyterhub==1.5.0
      - jupyterlab==3.2.3
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.8.2
      - jupyterlab-widgets==1.0.2
      - keras==2.6.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.3.1
      - mako==1.1.5
      - markdown==3.3.7
      - markupsafe==2.0.1
      - matplotlib==3.3.4
      - mdshare==0.4.1
      - mistune==0.8.4
      - multiprocess==0.70.12.2
      - nbclassic==0.3.4
      - nbclient==0.5.5
      - nbconvert==6.0.7
      - nbformat==5.1.3
      - nest-asyncio==1.5.1
      - nglview==3.0.3
      - notebook==6.4.5
      - numpy==1.19.5
      - oauthlib==3.1.1
      - opt-einsum==3.3.0
      - packaging==21.2
      - pamela==1.0.0
      - pandas==1.1.5
      - pandocfilters==1.5.0
      - parso==0.8.2
      - pathos==0.2.8
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==8.4.0
      - plotly==5.14.1
      - pox==0.3.0
      - ppft==1.6.6.4
      - prometheus-client==0.12.0
      - prompt-toolkit==3.0.22
      - protobuf==3.19.6
      - psutil==5.8.0
      - ptyprocess==0.7.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygments==2.10.0
      - pyopenssl==21.0.0
      - pyparsing==2.4.7
      - pyrsistent==0.18.0
      - python-dateutil==2.8.2
      - python-json-logger==2.0.2
      - pytraj==2.0.5
      - pytz==2021.3
      - pyyaml==6.0
      - pyzmq==22.3.0
      - requests==2.26.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - ruamel-yaml==0.17.17
      - ruamel-yaml-clib==0.2.6
      - scikit-learn==0.24.2
      - scipy==1.5.4
      - send2trash==1.8.0
      - six==1.15.0
      - sniffio==1.2.0
      - sqlalchemy==1.4.27
      - tenacity==8.2.2
      - tensorboard==2.6.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.0
      - tensorflow==2.6.2
      - tensorflow-estimator==2.6.0
      - tensorflow-probability==0.14.0
      - termcolor==1.1.0
      - terminado==0.12.1
      - testpath==0.5.0
      - threadpoolctl==3.0.0
      - tornado==6.1
      - tqdm==4.62.3
      - traitlets==4.3.3
      - typing-extensions==3.7.4.3
      - urllib3==1.26.7
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.2.1
      - werkzeug==2.0.3
      - wget==3.2
      - widgetsnbextension==3.5.2
      - wrapt==1.12.1
      - zipp==3.6.0
      - plotly
      - tensorboard==2.6.0 
      - tensorboard-data-server==0.6.1 
      - tensorboard-plugin-wit==1.8.0 
      - tensorflow==2.6.2 
      - tensorflow-estimator==2.6.0 
      - tensorflow-probability==0.14.0 
      - nbgitpuller
prefix: /usr/local/envs/engens-conda-env
